import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';

const context = JSON.parse(readFileSync('/tmp/moimashinani-test-context.json','utf8'));
process.env.DATABASE_URL = context.databaseUrl;
let prisma: typeof import('../src/lib/prisma').prisma;
const base = context.baseUrl;
const testId = randomUUID().slice(0,8);
const testIp = `2001:db8::${testId.slice(0,4)}:${testId.slice(4)}`;
let passed = 0;
function check(value: unknown, label: string) { assert.ok(value,label);passed++;console.log(`PASS ${label}`); }
async function request(path:string, options:{method?:string;body?:unknown;cookie?:string;origin?:string} = {}, status = 200) {
  const response = await fetch(base+path,{method:options.method || 'GET',headers:{...(options.body !== undefined ? {'Content-Type':'application/json'}:{}),...(options.cookie ? {Cookie:options.cookie}:{}),'X-Forwarded-For':testIp,Origin:options.origin || base},body:options.body === undefined ? undefined:JSON.stringify(options.body),signal:AbortSignal.timeout(90000)});
  const data = await response.json();
  assert.equal(response.status,status,`${options.method || 'GET'} ${path}: ${JSON.stringify(data)}`);
  return {response,data,cookie:response.headers.get('set-cookie')?.split(';')[0] || ''};
}
function emailToken(email:string) {
  const messages = JSON.parse(readFileSync(context.mailPath,'utf8')) as Array<{to:string[];message:string}>;
  const latest = messages.filter(message=>message.to.includes(email)).at(-1);
  assert.ok(latest,'Verification email delivered to local SMTP');
  const decoded = latest.message.replace(/=\r?\n/g,'').replace(/=([0-9A-F]{2})/g,(_,hex)=>String.fromCharCode(parseInt(hex,16)));
  const token = decoded.match(/\/verify\?token=([a-f0-9]{64})/)?.[1];
  assert.ok(token,'Email contains verification token');return token;
}
async function main() {
  prisma = (await import('../src/lib/prisma')).prisma;
  check((await request('/api/auth/me')).data.user === null,'anonymous account has no owned businesses');
  const admin = await request('/api/auth/login',{method:'POST',body:context.admin});
  check(admin.cookie.includes('mm_session='),'login establishes HTTP-only server session');
  check(admin.response.headers.get('set-cookie')?.includes('HttpOnly'),'session cookie is HTTP-only');
  await request('/api/admin/actions',{method:'POST',body:{action:'approve_listing',targetId:'biz_kevin_phones'}},401);
  await request('/api/businesses?status=all',{},401);
  await request('/api/reports',{},401);await request('/api/demand',{},401);await request('/api/bookings',{},401);
  check(true,'anonymous admin queues and mutations rejected');
  await request('/api/admin/enroll',{method:'POST',cookie:admin.cookie,origin:'https://evil.invalid',body:{}},403);
  check(true,'cross-site admin request rejected');
  const ownerEmail = `owner-${testId}@test.invalid`;
  const draft = {ownerEmail,ownerName:'Workflow Owner',name:`Workflow Shop ${testId}`,description:'A test workshop offering repairs and accessories near the campus gate.',primaryCategory:'phone-laptop-repair',zone:'kesses-centre',phone:'0712345678',whatsapp:'254712345678',landmark:'Test gate',services:[{id:'repair',name:'Phone repair',priceFrom:150}],hours:{Monday:{open:'08:00',close:'20:00'}}};
  const enrolled = await request('/api/admin/enroll',{method:'POST',cookie:admin.cookie,body:draft},201);
  const business = enrolled.data.business;
  check(enrolled.data.invitation.sent,'admin enrollment delivers owner verification email');
  check(business.status === 'ACTIVE' && business.verificationLevel === 'L2' && !business.isClaimed,'field enrollment publishes inspected business before owner claims account');
  check(!business.mapPin && !business.walkTime && business.photos.length === 0,'enrollment does not invent photos, coordinates or a walking distance');
  check(!JSON.stringify(enrolled.data).includes(emailToken(ownerEmail)),'verification token is never returned by enrollment API');
  await request('/api/auth/login',{method:'POST',body:{email:ownerEmail,password:'owner password 2026'}},401);
  await request('/api/auth/verify',{method:'POST',body:{token:emailToken(ownerEmail),password:'weak'}},400);
  const owner = await request('/api/auth/verify',{method:'POST',body:{token:emailToken(ownerEmail),password:'owner password 2026'}});
  await request('/api/auth/verify',{method:'POST',body:{token:emailToken(ownerEmail),password:'owner password 2026'}},400);
  check(true,'email verification is password validated and single-use');
  const mine = (await request('/api/auth/me',{cookie:owner.cookie})).data;
  check(mine.businesses.length === 1 && mine.businesses[0].id === business.id && mine.user.role === 'BUSINESS','owner sees only their own verified account');
  const publicProfile = (await request(`/api/businesses/${business.slug}`)).data;
  check(!publicProfile.ownerEmail && !publicProfile.ownerId && !publicProfile.claimCode && publicProfile.metrics.views === 0,'public profile excludes owner details and private analytics');
  const updated = await request(`/api/businesses/${business.slug}`,{method:'PATCH',cookie:owner.cookie,body:{tagline:'Updated by owner',status:'SUSPENDED',activeTier:'FEATURED',ownerId:mine.user.id,verificationLevel:'L0'}});
  check(updated.data.tagline === 'Updated by owner' && updated.data.status === 'ACTIVE' && updated.data.activeTier === 'NONE' && updated.data.verificationLevel === 'L2','owner can edit details without granting paid tiers or changing moderation');
  await request('/api/businesses/kevin-phones-laptops',{method:'PATCH',cookie:owner.cookie,body:{tagline:'unauthorized'}},403);
  await request('/api/businesses/kevin-phones-laptops/toggle-available',{method:'POST',cookie:owner.cookie},403);
  await request('/api/admin/enroll',{method:'POST',cookie:owner.cookie,body:draft},403);
  await request('/api/businesses?status=all',{cookie:owner.cookie},403);
  await request('/api/payments?businessId=biz_kevin_phones',{cookie:owner.cookie},403);
  check(true,'cross-business editing, billing and administrator access rejected');
  await request(`/api/businesses/${business.slug}`,{method:'PATCH',cookie:owner.cookie,body:{mapPin:{lat:0.283,lng:35.291}}});
  const removedPin = await request(`/api/businesses/${business.slug}`,{method:'PATCH',cookie:owner.cookie,body:{mapPin:null}});
  check(!removedPin.data.mapPin,'owner can update or remove an inaccurate map pin');
  const form = new FormData();
  const png = await sharp({create:{width:120,height:80,channels:3,background:'#335e41'}}).png().toBuffer();
  form.append('files',new Blob([new Uint8Array(png)],{type:'image/png'}),'shop.png');
  const photoResponse = await fetch(base+'/api/uploads',{method:'POST',headers:{Cookie:owner.cookie,Origin:base},body:form});
  assert.equal(photoResponse.status,201);const photos = await photoResponse.json();
  const photo = await fetch(new URL(photos.photos[0],base));
  check(photo.ok && photo.headers.get('content-type') === 'image/webp','owner photo uploads are validated, re-encoded and publicly served');
  await request(`/api/businesses/${business.slug}`,{method:'PATCH',cookie:owner.cookie,body:{photos:photos.photos,services:[{id:'repair',name:'Phone repair',priceFrom:150,photo:photos.photos[0]}]}});
  const badImage = new FormData();badImage.append('files',new Blob(['<svg><script>bad</script></svg>'],{type:'image/png'}),'fake.png');
  const rejectedPhoto = await fetch(base+'/api/uploads',{method:'POST',headers:{Cookie:owner.cookie},body:badImage});
  check(rejectedPhoto.status === 400,'disguised non-image file rejected');
  const today = new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Nairobi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  await request(`/api/businesses/${business.slug}/toggle-available`,{method:'POST',cookie:owner.cookie});
  const available = await request(`/api/businesses?q=${encodeURIComponent(business.name)}&availableNow=true`);
  check(available.data.results.some((item:{id:string})=>item.id === business.id),'owner availability reaches customer discovery');
  await request(`/api/businesses/${business.slug}`,{method:'PATCH',cookie:owner.cookie,body:{isTemporarilyClosed:true}});
  const paused = await request(`/api/businesses?q=${encodeURIComponent(business.name)}&availableNow=true`);
  check(!paused.data.results.some((item:{id:string})=>item.id === business.id),'temporary closure hides available-now listing');
  await request(`/api/businesses/${business.slug}`,{method:'PATCH',cookie:owner.cookie,body:{isTemporarilyClosed:false}});
  const bookingBody = {businessId:business.id,serviceName:'Phone repair',day:today,time:'Afternoon',studentName:'Test Customer',contactPhone:'0112345678',note:'Please call to confirm'};
  await request('/api/bookings',{method:'POST',body:{...bookingBody,day:'2020-01-01'}},400);
  await request('/api/bookings',{method:'POST',body:{...bookingBody,contactPhone:'wrong'}},400);
  await request('/api/bookings',{method:'POST',body:{...bookingBody,serviceName:'Invented service'}},400);
  const booking = await request('/api/bookings',{method:'POST',body:bookingBody},201);
  const inbox = await request(`/api/bookings?businessId=${business.id}`,{cookie:owner.cookie});
  check(inbox.data.some((item:{id:string;contactPhone:string})=>item.id === booking.data.id && item.contactPhone === '+254112345678'),'customer request reaches owner inbox with contact details');
  const confirmed = await request('/api/bookings',{method:'PATCH',cookie:owner.cookie,body:{id:booking.data.id,status:'CONFIRMED'}});
  check(confirmed.data.status === 'CONFIRMED','owner confirms customer request');
  await request('/api/bookings?businessId=biz_kevin_phones',{cookie:owner.cookie},403);
  await request('/api/bookings',{method:'PATCH',body:{id:booking.data.id,status:'CANCELLED'}},401);
  const report = await request('/api/reports',{method:'POST',body:{businessId:business.id,businessName:'Forged name',reason:'wrong_number',details:'Test issue'}},201);
  check(report.data.businessName === business.name,'report business identity is resolved on the server');
  await request('/api/reports',{cookie:owner.cookie},403);
  const reports = await request('/api/reports',{cookie:admin.cookie});check(reports.data.some((r:{id:string})=>r.id === report.data.id),'admin receives customer report');
  await request('/api/admin/actions',{method:'POST',cookie:admin.cookie,body:{action:'suspend_reported',targetId:report.data.id}});
  await request(`/api/businesses/${business.slug}`,{},404);
  await request('/api/bookings',{method:'POST',body:bookingBody},404);
  const directory = await request('/api/businesses');check(!directory.data.results.some((r:{id:string})=>r.id === business.id),'suspended businesses disappear from public discovery');
  await request('/api/admin/actions',{method:'POST',cookie:admin.cookie,body:{action:'restore_listing',targetId:business.id}});
  const secondReport = await request('/api/reports',{method:'POST',body:{businessId:business.id,reason:'other',details:'Resolved test issue'}},201);
  await request('/api/admin/actions',{method:'POST',cookie:admin.cookie,body:{action:'resolve_report',targetId:secondReport.data.id}});
  check((await prisma.problemReport.findUnique({where:{id:secondReport.data.id}}))?.status === 'RESOLVED','admin resolved reports persist the correct resolution state');
  const demand = await request('/api/demand',{method:'POST',body:{query:'Test service missing',zone:'kesses-centre',contactPhone:'0712345678'}},201);
  const demands = await request('/api/demand',{cookie:admin.cookie});check(demands.data.some((d:{id:string})=>d.id === demand.data.id),'customer service demand reaches admin');
  await request('/api/events',{method:'POST',body:{businessId:business.id,type:'view'}});
  const metrics = (await request(`/api/businesses/${business.slug}`,{cookie:owner.cookie})).data.metrics;
  check(metrics.views === 1 && metrics.bookingRequests === 1,'real interactions update owner analytics');
  await request('/api/events',{method:'POST',body:{businessId:business.id,type:'booking'}},400);
  await request('/api/payments',{method:'POST',cookie:owner.cookie,body:{businessId:business.id,planId:'FEATURED',weeks:-1}},400);
  await request('/api/payments',{method:'POST',cookie:owner.cookie,body:{businessId:business.id,planId:'FEATURED',weeks:1}},503);
  await request('/api/payments/fake/settle',{method:'POST',body:{success:true}},410);
  check((await request(`/api/businesses/${business.slug}`,{cookie:owner.cookie})).data.activeTier === 'NONE','missing provider credentials and fake settlement never activate promotions');
  const pendingEmail = `pending-${testId}@test.invalid`;
  const pending = await request('/api/businesses',{method:'POST',body:{...draft,ownerEmail:pendingEmail,name:`Pending Shop ${testId}`,status:'ACTIVE',isClaimed:true,activeTier:'FEATURED'}},201);
  check(pending.data.business.status === 'PENDING' && pending.data.business.activeTier === 'NONE' && !pending.data.business.isClaimed,'public enrollment cannot publish or self-award promotions');
  await request(`/api/businesses/${pending.data.business.slug}`,{},404);
  await request('/api/admin/actions',{method:'POST',cookie:admin.cookie,body:{action:'reject_listing',targetId:pending.data.business.id}},400);
  await request('/api/admin/actions',{method:'POST',cookie:admin.cookie,body:{action:'reject_listing',targetId:pending.data.business.id,reason:'Please confirm the landmark'}});
  const pendingOwner = await request('/api/auth/verify',{method:'POST',body:{token:emailToken(pendingEmail),password:'pending owner password 2026'}});
  const rejected = await request(`/api/businesses/${pending.data.business.slug}`,{cookie:pendingOwner.cookie});
  check(rejected.data.status === 'REJECTED' && rejected.data.moderationReason === 'Please confirm the landmark','rejected owner can see the persisted reason and correct their details');
  await request('/api/admin/actions',{method:'POST',cookie:admin.cookie,body:{action:'approve_listing',targetId:pending.data.business.id}});
  check((await request(`/api/businesses/${pending.data.business.slug}`)).data.verificationLevel === 'L0','listing approval does not falsely claim field verification');
  const expiredEmail = `expired-${testId}@test.invalid`;
  // Intentionally disable delivery only in this process. The HTTP server's
  // local SMTP configuration remains available for the recovery step.
  process.env.APP_URL = base;
  delete process.env.SMTP_HOST;
  const failedEnrollRoute = await import('../app/api/admin/enroll/route');
  const {NextRequest} = await import('next/server');
  const failedDelivery = await failedEnrollRoute.POST(new NextRequest(base+'/api/admin/enroll',{method:'POST',headers:{Cookie:admin.cookie,'Content-Type':'application/json',Origin:base},body:JSON.stringify({...draft,ownerEmail:expiredEmail,name:`Delivery Recovery Shop ${testId}`})}));
  const failedPayload = await failedDelivery.json();
  assert.equal(failedDelivery.status,201,`Delivery recovery enrollment: ${JSON.stringify(failedPayload)}`);
  check(!failedPayload.invitation.sent && failedPayload.business.id,'email configuration failure preserves enrollment with a recoverable delivery error');
  await request('/api/admin/invitations',{method:'POST',cookie:admin.cookie,body:{businessId:failedPayload.business.id}});
  const expiredToken = emailToken(expiredEmail);
  await prisma.verificationToken.updateMany({where:{businessId:failedPayload.business.id,usedAt:null},data:{expiresAt:new Date(0)}});
  await request('/api/auth/verify',{method:'POST',body:{token:expiredToken,password:'recovery owner password 2026'}},400);
  const resent = await request('/api/admin/invitations',{method:'POST',cookie:admin.cookie,body:{businessId:failedPayload.business.id}});
  check(resent.data.invitation.sent,'admin can recover email delivery and resend an expired invitation');
  await request('/api/auth/verify',{method:'POST',body:{token:emailToken(expiredEmail),password:'recovery owner password 2026'}});
  await request('/api/auth/verify',{method:'POST',body:{token:expiredToken,password:'recovery owner password 2026'}},400);
  const reset = await request('/api/auth/request-link',{method:'POST',body:{email:ownerEmail}});check(reset.data.success,'owner can request password reset email');
  const resetToken = emailToken(ownerEmail);
  await request('/api/auth/verify',{method:'POST',body:{token:resetToken,password:'new owner password 2026'}});
  check((await request('/api/auth/me',{cookie:owner.cookie})).data.user === null,'password reset revokes old sessions');
  const loggedBack = await request('/api/auth/login',{method:'POST',body:{email:ownerEmail,password:'new owner password 2026'}});
  await request('/api/auth/logout',{method:'POST',cookie:loggedBack.cookie});
  check((await request('/api/auth/me',{cookie:loggedBack.cookie})).data.user === null,'logout revokes the server session');
  check(await prisma.business.count({where:{id:{in:[business.id,pending.data.business.id,failedPayload.business.id]}}}) === 3,'all workflow records persisted in PostgreSQL');
  writeFileSync('/tmp/moimashinani-workflow-results.json',JSON.stringify({passed,testId,businessId:business.id,slug:business.slug,ownerEmail},null,2));
  console.log(`All ${passed} workflow checks passed.`);
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>prisma?.$disconnect());
