import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { chromium, expect, type Page } from '@playwright/test';
import sharp from 'sharp';

const context = JSON.parse(readFileSync('/tmp/moimashinani-test-context.json','utf8'));
const base = context.baseUrl;
const ownerEmail = `browser-${randomUUID().slice(0,8)}@test.invalid`;
const ownerPassword = 'browser owner password 2026';
const shopName = `Browser Visit Shop ${randomUUID().slice(0,5)}`;
const addressId = randomUUID().slice(0,8);
const testHeaders = {'X-Forwarded-For':`2001:db8::${addressId.slice(0,4)}:${addressId.slice(4)}`};
const errors:string[] = [];
function track(page:Page) { page.setDefaultTimeout(45000);page.setDefaultNavigationTimeout(90000);page.on('pageerror',error=>errors.push(error.message)); }
function tokenFromMail() {
  const mail = JSON.parse(readFileSync(context.mailPath,'utf8')) as Array<{to:string[];message:string}>;
  const latest = mail.filter(message=>message.to.includes(ownerEmail)).at(-1)!;
  const text = latest.message.replace(/=\r?\n/g,'').replace(/=([0-9A-F]{2})/g,(_,hex)=>String.fromCharCode(parseInt(hex,16)));
  return text.match(/\/verify\?token=([a-f0-9]{64})/)![1];
}
async function main() {
  const browser = await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE});
  mkdirSync('/tmp/moimashinani-browser',{recursive:true});
  try {
    const adminContext = await browser.newContext({baseURL:base,extraHTTPHeaders:testHeaders,viewport:{width:1440,height:1000}});
    const admin = await adminContext.newPage();track(admin);
    await admin.goto('/login?next=/admin/enroll');
    await admin.getByLabel('Email address').fill(context.admin.email);await admin.getByLabel('Password',{exact:true}).fill(context.admin.password);
    await admin.getByRole('button',{name:'Sign in',exact:true}).click();
    await expect(admin.getByRole('heading',{name:'Enroll a business',exact:true})).toBeVisible({timeout:90000});
    await admin.getByLabel('Owner name *',{exact:true}).fill('Browser Owner');await admin.getByLabel('Owner email *',{exact:true}).fill(ownerEmail);
    await admin.getByRole('combobox',{name:'Category',exact:true}).selectOption('phone-laptop-repair');
    await admin.getByLabel('Business name *',{exact:true}).fill(shopName);await admin.getByLabel('Description *',{exact:true}).fill('We repair phones and sell accessories for the campus community.');
    await admin.getByLabel('Phone number *',{exact:true}).fill('0712345678');await admin.getByLabel('Nearby landmark *',{exact:true}).fill('Across the campus gate');
    await admin.getByLabel('Product or service name',{exact:true}).fill('Screen diagnosis');await admin.getByLabel('Price from (KES)',{exact:true}).fill('150');
    const photo = await sharp({create:{width:300,height:200,channels:3,background:'#335e41'}}).png().toBuffer();
    await admin.getByLabel('Business and product photos',{exact:true}).setInputFiles({name:'shop.png',mimeType:'image/png',buffer:photo});
    await expect(admin.getByRole('img',{name:'Business photo 1',exact:true})).toBeVisible({timeout:45000});
    await admin.getByLabel('Product photo',{exact:true}).selectOption({label:'Photo 1 (cover)'});
    for (const width of [320, 360, 390, 430, 768]) {
    await admin.setViewportSize({width,height:844});
    const clippedInputs = await admin.locator('input[type="time"]').evaluateAll((inputs) =>
    inputs.filter(input => {const rect = input.getBoundingClientRect(); return rect.left < -1 || rect.right > window.innerWidth + 1;})
    .map(input => input.getAttribute('aria-label')));
    assert.deepEqual(clippedInputs,[],`Opening hours time inputs clipped at ${width}px`);
    }
    await expect(admin.getByLabel('Sunday opening time',{exact:true})).toBeDisabled();
    await admin.getByLabel('Sunday closed',{exact:true}).uncheck();
    await expect(admin.getByLabel('Sunday opening time',{exact:true})).toBeEnabled();
    await admin.getByLabel('Sunday closed',{exact:true}).check();
    await admin.setViewportSize({width:390,height:844});
    await admin.screenshot({path:'/tmp/moimashinani-browser/mobile-enrollment.png',fullPage:true});
    assert.ok(await admin.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth),'Mobile enrollment has no horizontal overflow');
    const enrollmentResponse = admin.waitForResponse(response=>response.url().endsWith('/api/admin/enroll') && response.request().method()==='POST');
    await admin.getByRole('button',{name:'Enroll business & email owner',exact:true}).click();
    const enrollment = await (await enrollmentResponse).json();assert.ok(enrollment.invitation.sent);
    await expect(admin.getByRole('heading',{name:`${shopName} has been enrolled`})).toBeVisible();
    const business = enrollment.business;
    await admin.screenshot({path:'/tmp/moimashinani-browser/enrollment-success.png',fullPage:true});
    console.log('PASS browser admin login, field enrollment, gallery/product photo and emailed invitation');
    const ownerContext = await browser.newContext({baseURL:base,extraHTTPHeaders:testHeaders,viewport:{width:1280,height:900}});
    const owner = await ownerContext.newPage();track(owner);
    await owner.goto(`/verify?token=${tokenFromMail()}`);
    await owner.getByLabel('Password',{exact:true}).fill(ownerPassword);await owner.getByLabel('Confirm password',{exact:true}).fill(ownerPassword);
    await owner.getByRole('button',{name:'Verify & open my account',exact:true}).click();
    await owner.waitForURL(`**/dashboard/${business.slug}`,{timeout:90000});
    await expect(owner.getByRole('heading',{name:shopName,exact:true})).toBeVisible({timeout:45000});
    await owner.getByRole('button',{name:'details',exact:true}).click();
    await owner.getByLabel('Tagline',{exact:true}).fill('Browser-tested owner update');
    await owner.getByRole('button',{name:'Save business information',exact:true}).click();
    await expect(owner.getByText('Changes saved.',{exact:true})).toBeVisible();
    const profile = await (await ownerContext.request.get(`/api/businesses/${business.slug}`)).json();assert.equal(profile.tagline,'Browser-tested owner update');
    console.log('PASS browser owner email verification, automatic login and persistent profile editing');
    await owner.getByRole('button',{name:'hours',exact:true}).click();
    await owner.getByLabel('Monday opening time',{exact:true}).fill('09:00');await owner.getByRole('button',{name:'Save opening hours',exact:true}).click();
    await expect(owner.getByText('Changes saved.',{exact:true})).toBeVisible();
    await owner.screenshot({path:'/tmp/moimashinani-browser/owner-hours.png',fullPage:true});
    await owner.getByRole('button',{name:'services',exact:true}).click();
    await owner.getByLabel('Name',{exact:true}).fill('Charging cable');
    await owner.getByLabel('Starting price (KSh, optional)',{exact:true}).fill('120');
    await owner.getByRole('button',{name:'Add item',exact:true}).click();
    await expect(owner.getByText('Charging cable',{exact:true})).toBeVisible();
    await owner.getByRole('button',{name:'Remove Charging cable',exact:true}).click();
    await expect(owner.getByText('Charging cable',{exact:true})).not.toBeVisible();
    await owner.getByRole('button',{name:'overview',exact:true}).click();
    await owner.getByRole('button',{name:'Available now for 4 hours',exact:true}).click();
    await expect(owner.getByRole('button',{name:'Turn off Available now',exact:true})).toBeVisible();
    await owner.getByRole('button',{name:'Mark temporarily closed',exact:true}).click();
    await expect(owner.getByRole('button',{name:'Reopen business',exact:true})).toBeVisible();
    await owner.getByRole('button',{name:'Reopen business',exact:true}).click();
    await expect(owner.getByRole('button',{name:'Mark temporarily closed',exact:true})).toBeVisible();
    console.log('PASS browser owner hours, product CRUD, availability and temporary closure controls');

    const customerContext = await browser.newContext({baseURL:base,extraHTTPHeaders:testHeaders,viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    const customer = await customerContext.newPage();track(customer);
    await customer.goto(`/b/${business.slug}`);
    await expect(customer.getByRole('heading',{name:shopName,exact:true})).toBeVisible({timeout:90000});
    await customer.getByRole('button',{name:'Request Booking',exact:true}).click();
    await customer.getByLabel('Your name',{exact:true}).fill('Browser Student');await customer.getByLabel('Your phone / WhatsApp',{exact:true}).fill('0712345678');
    await customer.getByRole('button',{name:'Submit booking request',exact:true}).click();
    await expect(customer.getByRole('heading',{name:'Booking request saved',exact:true})).toBeVisible();
    await expect(customer.getByRole('link',{name:'Continue on WhatsApp',exact:true})).toHaveAttribute('href',/wa\.me\/254712345678/);
    await customer.screenshot({path:'/tmp/moimashinani-browser/customer-booking.png',fullPage:true});
    console.log('PASS mobile customer profile, booking submission and WhatsApp handoff');
    await owner.getByRole('button',{name:/^bookings/i}).click();await owner.getByRole('button',{name:'Refresh',exact:true}).last().click();
    await expect(owner.getByText('Browser Student',{exact:true})).toBeVisible();
    await owner.getByLabel("Status for Browser Student's booking",{exact:true}).selectOption('CONFIRMED');
    await expect(owner.getByText('Booking status updated.',{exact:true})).toBeVisible();
    await owner.screenshot({path:'/tmp/moimashinani-browser/owner-bookings.png',fullPage:true});
    console.log('PASS browser customer request reaches owner inbox and can be confirmed');
    await owner.goto(`/promote/${business.slug}`);
    await expect(owner.getByRole('heading',{name:shopName,exact:true})).toBeVisible();
    await owner.getByRole('radio',{name:/Recommended/}).check();
    await owner.getByRole('button',{name:'2 weeks',exact:true}).click();
    await owner.getByRole('button',{name:'Pay KSh 200 with IntaSend',exact:true}).click();
    await expect(owner.getByRole('alert').filter({hasText:'Payments are not configured.'})).toHaveText('Payments are not configured. Please contact the administrator.');
    assert.ok(owner.url().includes(`/promote/${business.slug}`),'Configuration failure keeps owner on checkout');
    await owner.screenshot({path:'/tmp/moimashinani-browser/checkout-configuration.png',fullPage:true});
    console.log('PASS browser promotion pricing, checkout request and recoverable missing-provider configuration');
    await customer.getByRole('button',{name:'Done',exact:true}).click();
    await customer.goto(`/dashboard/${business.slug}`);
    await expect(customer.getByRole('heading',{name:'Sign in to your account',exact:true})).toBeVisible();
    await owner.goto('/admin');await expect(owner.getByRole('heading',{name:'Account access required',exact:true})).toBeVisible();
    console.log('PASS browser anonymous/owner role access gates');
    await admin.goto('/admin');await expect(admin.getByRole('heading',{name:'Business enrollment & admin console',exact:true})).toBeVisible({timeout:60000});
    const ownerPrivate = await (await adminContext.request.get('/api/auth/me')).json();assert.ok(ownerPrivate.businesses.some((b:{id:string;emailVerifiedAt?:string})=>b.id===business.id && b.emailVerifiedAt));
    await admin.getByRole('button',{name:/All listings/}).click();
    await admin.getByLabel('Find a business',{exact:true}).fill(shopName);
    await admin.getByRole('button',{name:'Suspend listing',exact:true}).click();
    await expect(admin.getByRole('button',{name:'Restore listing',exact:true})).toBeVisible();
    await admin.getByRole('button',{name:'Restore listing',exact:true}).click();
    await expect(admin.getByRole('button',{name:'Suspend listing',exact:true})).toBeVisible();
    console.log('PASS browser admin listing suspension and restoration');
    await admin.screenshot({path:'/tmp/moimashinani-browser/admin-console.png',fullPage:true});
    assert.deepEqual(errors,[],`Browser runtime errors: ${errors.join('; ')}`);
    writeFileSync('/tmp/moimashinani-browser/results.json',JSON.stringify({passed:10,shopName,slug:business.slug,errors},null,2));
    console.log('All 10 browser journeys passed with no uncaught browser errors.');
  } finally {await browser.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
